### PR TITLE
Halt installation of unused documentation files

### LINKED ISSUE #1: ./configure changes
The sources for the build scripts are not in this repo.

Would you consider allowing patches that would optionally not include appindicator3-0.1 for systems that do not use?

Also would you consider allowing a patch to have a binary install only option so that the zero byte AUTHORS ChangeLog NEWS and the non-zero byte but non-documentation files COPYING INSTALL do not get installed?

### PR DESCRIPTION
**Pull request by bexelbie**
AUTHORS, ChangeLog, NEWS, and README are not used in this project.

autogen.sh should be run to regenerate configuration files including the
Makefile.in, Makefile and configure files. These can be committed after
this patch is applied.

Fixes #1

### CODE REVIEW

**Comment by bexelbie** [comment]
Let me know if this works please.  I haven't got Anjuta installed so I tested it with the CLI tools.  I use a newer version of libtool than you do so I didn't commit my versions output.

**Review by thejambi — APPROVED** [review]
Approving because I don't know enough to say otherwise :)

**Comment by bexelbie** [comment]
Cool.  Do you mind merging it and testing it with your build system?

**Comment by bexelbie** [comment]
Any chance of a merge here?

**Pull request merged**
